/* Modelagem Básica */

    CLIENTE 

    NOME - CARACTER (30)
    CPF - NUMERICO (11)
    EMAIL - CARACTER (30)
    TEFELONE - CARACTER (30)
    ENDERECO - CARACTER (100)
    SEXO - CARACTER (1)

/* PROCESSOS DE MODELAGEM */

    /*FASE 01 E FASE 02 - AD DE DADOS*/

        MODELAGEM CONCEITUAL - RASCUNHO
        MODELAGEM LÓGICA - QUALQUER PROGRAMA DE MODELAGEM

/*FASE 3 - DBA / AD */

    MODELAGEM FÍSICA - SCRIPTS DE BANCO

/* INICIANDO A MODELAGEM FÍSICA */

    /* CRIANDO O BANCO DE DADOS */

        CREATE DATABASE EXEMPLO 
        CREATE DATABASE PROJETO; 

/* CONECTANDO-SE AO BANCO */

    USE PROJETO;

/* CRIANDO A TABELA DE CLIENTES */

    CREATE TABLE CLIENTE (
    NOME VARCHAR (30),
    SEXO CHAR (1),
    EMAIL VARCHAR (30),
    CPF INT (11),
    TELEFONE VARCHAR (30),
    ENDERECO VARCHAR (100)

);

/* VERIFICANDO AS TABELAS DO BANCO*/

    SHOW TABLE;

/* EXIBINDO A ESTRUTURA DE UMA TABELA */

    DESC CLIENTE;

/* SINTAXE BÁSICA DE INSERÇÃO  - INSERT INTO TABELA */

    /* FORMA 01 - OMITINDO AS COLUNAS */

        INSERT INTO CLIENTE VALUES ('JOAO', 'M', 'JOAO@GMAIL.COM', 988638273, '22923110', 'MAIA LACERDA - ESTACIO - RIO DE JANEIRO - RJ');

        INSERT INTO CLIENTE VALUES ('CELIA', 'F', 'CELIA@GMAIL.COM', 541521456, '25078869', 'RIACHUELO - CENTRO - RIO DE JANEIRO - RJ');

        INSERT INTO CLIENTE VALUES ('JORGE', 'M', NULL, 885755896, '58748895', 'OSCAR CURY - BOM RETIRO - PATOS DE MINAS - MG');


    /* FORMA 02 - COLOCANDO AS COLUNAS */

        INSERT INTO CLIENTE (NOME, SEXO, ENDERECO, TELEFONE, CPF) VALUES ('LILIAN', 'F', 'SENADOR SOARES - TIJUCA - RIO DE JANEIRO - RJ', 
        '947785696', 887774856);

    /* FORMA 03 - INSERT COMPACTO - SOMENTE MYSQL */

        INSERT INTO CLIENTE VALUES ('ANA', 'F', 'ANA@GLOBO.COM', 85548962, '548556985', 'PRES ANTONIO CARLOS - CENTRO - SAO PAULO - SP'), 
        ('CARLA','F','CARLA@TERATI.COM.BR', 7745828, '66587458', 'SAMUEL SILVA - CENTRO - BELO HORIZONTE - MG');

/* COMANDO SELECT - SELEÇÃO, PROJEÇÃO E JUNÇÃO */

    SELECT NOW () ; 

    SELECT 'FELIPE MAFRA';

    SELECT 'BANCO DE DADOS';

/* ALIAS DE COLUNAS */

    SELECT NOME as CLIENTE, SEXO, EMAIL FROM CLIENTE;

    SELECT NOME, SEXO, EMAIL, ENDERECO FROM CLIENTE; 

/* FILTRANDO DADOS COM WHERE E LIKE */

    SELECT NOME, TELEFONE FROM CLIENTE;

/* TRAZER TODOS OS DADOS */

    SELECT * FROM CLIENTE;

/* FILTRANDO */

    SELECT NOME, SEXO FROM CLIENTE
    WHERE SEXO = 'M';

    SELECT NOME, ENDERECO FROM CLIENTE
    WHERE SEXO = 'F';

    SELECT NOME, SEXO FROM CLIENTE
    WHERE ENDERECO = 'RJ';

/* UTILIZANDO O LIKE */

    SELECT NOME, SEXO FROM CLIENTE
    WHERE ENDERECO LIKE '%RJ';

    SELECT NOME, SEXO , ENDERECO FROM CLIENTE
    WHERE ENDERECO LIKE 'OSCAR CURY%';

    SELECT NOME, SEXO , ENDERECO FROM CLIENTE
    WHERE ENDERECO LIKE '%TIJUCA%';

    SELECT NOME_DO_AUTOR
    FROM LIVRO
    WHERE SEXO_DO_AUTOR = 'MASCULINO'
    AND (UF_DA_EDITORA = 'SP' OR UF_DA_EDITORA = 'RJ');

/* UTILIZANDO OR */

    SELECT NOME, SEXO, ENDERECO FROM CLIENTE
    WHERE SEXO = 'M' OR ENDERECO LIKE '%RJ';

    SELECT NOME, SEXO, ENDERECO FROM CLIENTE 
    WHERE SEXO = 'F' OR ENDERECO LIKE '%ESTACIO';

/* UTILIZANDO AND */

    SELECT NOME, SEXO, ENDERECO 
    FROM CLIENTE
    WHERE SEXO = 'M' AND ENDERECO LIKE '%RJ';

    SELECT NOME, SEXO, ENDERECO 
    FROM CLIENTE 
    WHERE SEXO = 'F' 
    AND ENDERECO LIKE '%ESTACIO';

/* COUNT (*), GROUP BY, PERFORMANCE COM OPERADORES LOGICOS */

    /* CONTANDO OS REGISTROS DE UMA TABELA */

        SELECT COUNT(*) AS "Quantidade de Registros de Tab. Cliente"  
        FROM Cliente;

        SELECT COUNT(*)
        FROM Cliente;

        SELECT SEXO, COUNT(*)
        FROM Cliente;

/* OPERADOR GROUP BY */

    SELECT SEXO, COUNT(*) AS Contagem
    FROM Cliente
    GROUP BY SEXO;

/* PERFORMANCE EM OPERADORES LOGICOS */

    /* 1 MILHAO DE REGISTROS */

        PARA CONTAR
        SELECT COUNT(*) FROM CLIENTE;

        SELECT SEXO, COUNT(*) FROM CLIENTE
        GROUP By SEXO;

        SELECT CIDADE, COUNT(*) FROM CLIENTE
        GROUP BY CIDADE;

        CONDICAO
        SEXO = F

/* Exercicio 2 */

    /* FILTRANDO VALORES NULOS / IS NULL IS NOT NULL */

        SELECT Nome, Sexo, Endereco
        FROM Cliente
        WHERE Email = NULL;

        SELECT Nome, Sexo, Endereco
        FROM Cliente
        WHERE Email IS NULL;

        SELECT Nome, Sexo, Endereco
        FROM Cliente
        WHERE Email IS NOT NULL;

/* UTILIZANDO O UPDATE PARA ATUALIZAR VALORES */

        SELECT Nome, Email
        FROM Cliente;

        UPDATE Cliente
        SET Email = 'LILIAN@HOTMAIL.COM'
        WHERE Nome = 'Lilian';

        UPDATE Cliente
        SET Email = 'JORGE@GMAIL.COM'
        WHERE Nome = 'JORGE';





